// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mexwhyhuqbnrjfqzccoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1leHdoeWh1cWJucmpmcXpjY29pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MzgzNzEsImV4cCI6MjA1NzUxNDM3MX0.sF2i56Bb1iTsEuZPjsawYRA0TB3uOyfTKoeObrJB0uY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);